#!/bin/bash
echo "Enter Task no"
read tsk
if [ $tsk = 1 ];
then
        echo "Enter your name"
        read name
        echo "Enter your email"
        read email
        echo "Enter you college name"
        read college
        #Check docker container running or not
        if [ "$(docker ps | grep -o myweb)" > 1 ]
        then
             if curl -s --head  --request GET http://localhost:8080 | grep "200 OK" > /dev/null; then
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Docker container is running"
                echo "Task1 completed successfully"
             else
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task1 is not completed "
                echo "localhost:8080 is DOWN"
             fi
        fi

elif [ $tsk = 3 ];
then
        echo "Enter your name"
        read name
        echo "Enter your email"
        read email
        echo "Enter you college name"
        read college
        ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mydb)
       if ! mysql -u root -h $ip -pmypass -e ' use Class' 2> /dev/null ; then
                echo "Database is not Created"
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task3 is not completed"
       else
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Database is Created"
                echo "Task3 completed Successfully"

       fi
elif [ $tsk = 4 ];
then
        echo "Enter your name"
        read name
        echo "Enter your email"
        read email
        echo "Enter you college name"
        read college

        ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mydb)
        if [ $(echo "SELECT COUNT(*) FROM mysql.user WHERE user = 'harry'" | mysql -h $ip -pmypass | tail -n1) -gt 0 ]
        then
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task4 completed Successfully"
        else
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task4 is not completed"
                echo "User doesn't exist"
        fi

elif [ $tsk = 2 ];
then
        echo "Enter your name"
        read name
        echo "Enter your email"
        read email
        echo "Enter you college name"
        read college

        if [ "$(docker ps | grep -o mydb)" > 1 ]
        then
                        echo "name: $name"
                        echo "email id: $email"
                        echo "college: $college"
                        echo "Task2 is completed successfully"
        else
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task2 is not completed"
        fi

elif [ $tsk = 5 ];
then
        echo "Enter your name"
        read name
        echo "Enter your email"
        read email
        echo "Enter you college name"
        read college

        if id "harry" >/dev/null 2>&1; then
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task5 completed Successfully"
        else
                echo "name: $name"
                echo "email id: $email"
                echo "college: $college"
                echo "Task5 is not completed"
                echo "User does not exist"
        fi

else
        echo "This is not valid task no"

fi
